- name: Simple A record (IPV4 address) lookup for kubemaster
  set_fact:
    kubemaster: "{{ lookup('dig', 'kubemaster')}}"

- name: Update apt cache
  become: yes
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: If needed, install Python
  become: yes
  apt:
    pkg:
     - python3-dev
     - python3-pip

- name: Install base dependencies
  become: yes
  apt:
    name:
      - snapd
    state: present

- name: Check is ufw installed
  shell: command -v ufw >/dev/null 2>&1
  register: is_ufw_exist
  ignore_errors: yes

- name: Disabling ufw
  command: ufw disable
  become: yes
  when: is_ufw_exist.rc == 0

- name: Set ip forwarding
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes

- name: Disable Swap
  command: swapoff -a

- name: Install microk8s
  become: yes
  snap:
    name: microk8s
    classic: yes
    channel: "{{ microk8s_version }}"

- name: Add User to the microk8s group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: yes

- name: Change the owner of the .kube folder
  become: yes
  file:
    owner: "{{ ansible_user }}"
    recurse: yes
    path: ~/.kube

- name: Update Microk8s docker-daemon.json file
  become: yes
  template:
    src: "docker-daemon.json"
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "root"

- name: Microk8s status
  shell: microk8s.status --wait-ready
  args:
    executable: /bin/bash

- name: Allow Privileged for Kubelet (needed by Elasticsearch Helm chart)
  lineinfile:
    dest: /var/snap/microk8s/current/args/kubelet
    line: "--allow-privileged=true"
    state: present

- name: Allow Privileged for K8s Apiserver (needed by Elasticsearch Helm chart)
  lineinfile:
    dest: /var/snap/microk8s/current/args/kube-apiserver
    line: "--allow-privileged=true"
    state: present

- name: Set File Descriptor Limits for Microk8s
  lineinfile:
    dest: /var/snap/microk8s/current/args/containerd-env
    line: "ulimit -n 65536"
    state: present

#- name: Add Insecure Registries
#  import_tasks: add-insecure-registries.yml

- name: Stop Microk8s
  shell: microk8s.stop
  args:
    executable: /bin/bash

- name: Start Microk8s
  shell: microk8s.start
  args:
    executable: /bin/bash

- name: Microk8s status
  shell: microk8s.status --wait-ready
  args:
    executable: /bin/bash

- name: Microk8s inspect
  shell: microk8s.inspect
  args:
    executable: /bin/bash

  # - name: Alias kubectl
  #   shell: " snap alias microk8s.kubectl kubectl"
  #   args:
  #     executable: /bin/bash

# - name: Alias docker
#   shell: " snap alias microk8s.docker docker"
#   args:
#     executable: /bin/bash

- name: Enable dns
  shell: "microk8s.enable dns"
  args:
    executable: /bin/bash

- name: Enable ingress
  shell: "microk8s.enable ingress"
  args:
    executable: /bin/bash

- name: Enable storage
  shell: "microk8s.enable storage"
  args:
    executable: /bin/bash

- name: Enable K8s Dashboard
  shell: ".enable dashboard"
  when: k8s_dashboard|default(False)|bool == True
  args:
    executable: /bin/bash
