---
- hosts: all
  become: true

  tasks:
    - name: Simple A record (IPV4 address) lookup for kubemaster
      set_fact:
        ip_addr: "{{ lookup('dig', 'kubemaster')}}"

    - name: Look at the DNS name
      ansible.builtin.debug:
        msg: "{{ ip_addr }}"
